services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./homepage:/srv/homepage
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
