name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment: production
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          envs: SOPS_AGE_KEY
          script: |
            cd ~/infra
            git pull
            ./scripts/deploy_infra.sh
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
